config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pictures
  resources :user_cars
  resources :cars
  resources :destination_tags
  resources :destination_road_trips
  resources :comments
  resources :user_road_trips
  resources :tags
  resources :destinations
  resources :road_trips
  resources :users, path: 'user/profiles'

end

app/models/road_trip.rb
class RoadTrip < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :total_miles, presence: true
  validates :author_id, presence: true

  has_many :user_road_trips
  has_many :users, through: :user_road_trips
  has_many :destination_road_trips
  has_many :destinations, through: :destination_road_trips
  has_many :tags, through: :destinations
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :destinations
  accepts_nested_attributes_for :destination_road_trips
  accepts_nested_attributes_for :tags

  def total_destinations
    self.destinations.size
  end

  def destinations_attributes=(destination_attributes)
    destination_attributes.values.each do |destination_attribute|
      destination = Destination.find_or_initialize_by(destination_attribute)
      if destination.save
        self.destination_road_trips.create(destination_id: destination.id)
      end
    end
  end

  def destination_road_trips_attributes=(destination_road_trips_attributes)
    trips_to_update = destination_road_trips_attributes.values.select {|destination_road_trip_attribute| !destination_road_trip_attribute[:id].nil?}
    trips_to_update.each do |drt|
      if drt[:destination_order].to_i >= 0 && drt[:destination_order].to_i <= trips_to_update.length
        if !DestinationRoadTrip.where(id: drt[:id]).empty?
          DestinationRoadTrip.where(id: drt[:id]).first.update(destination_order: drt[:destination_order])
        end
      end
    end
  end
end

app/controllers/road_trips_controller.rb
class RoadTripsController < ApplicationController
  before_action :set_road_trip, only: [:show, :edit, :update, :destroy]
  before_action :set_destinations, only: [:new, :edit, :update]

  def index
    @road_trips = RoadTrip.all
  end

  def show
  end

  def new
    @road_trip = RoadTrip.new
  end

  def edit
  end

  def create
    @road_trip = RoadTrip.new(road_trip_params)

    if @road_trip.save
      redirect_to @road_trip
    else
      render :new
    end
  end

  def update
    if @road_trip.update(road_trip_params)
      redirect_to @road_trip
    else
      render :edit
    end
  end

  def destroy
    @road_trip.destroy
    redirect_to road_trips_url
  end

  private
    def set_road_trip
      @road_trip = RoadTrip.find(params[:id])
    end

    def set_destinations
      @destinations = Destination.all
    end

    def road_trip_params
      params.require(:road_trip).permit(
        :title, :description, :total_miles, :author_id,
        destination_ids:[], destinations_attributes: [:name, :description, :city, :state, :street_address, tags: [:title]],
        destination_road_trips_attributes: [:id, :destination_order]
        )
    end
end

app/helpers/road_trips_helper.rb
module RoadTripsHelper
  def find_trip(id)
    RoadTrip.find(id)
  end

  def trip_author(author_id)
    User.find(author_id)
  end
end

app/views/road_trips/_form.html.erb
<div class="card mb-3">
  <%= form_for(@road_trip) do |f| %>
  <div class="card mb-3" style="height: 100%; width:46%; float:left; margin:1px">
    <div class="card-body">
      <% if @road_trip.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@road_trip.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @road_trip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div><br>

      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, size: "70x5" %>
      </div><br>

      <br>
      <div class="form-group">
        <%= f.label :total_miles %><br>
        <%= f.number_field :total_miles %>
      </div>
    </div>
    <div class="card-body">
      <h3 class="card-header">Create A New Destination</h3><br>
      <%= f.fields_for :destinations, @road_trip.destinations.build do |destinations_fields| %>
        <%= destinations_fields.label :name %>
        <%= destinations_fields.text_field :name %><br>
        <%= destinations_fields.label :description %>
        <%= destinations_fields.text_area :description, size: "75x5" %>
        <%= destinations_fields.label :city %>
        <%= destinations_fields.text_field :city %> ,
        <%= destinations_fields.label :state %>
        <%= destinations_fields.text_field :state %><br>
        <%= destinations_fields.label :street_address %>
        <%= destinations_fields.text_field :street_address %><br><br>
        <h6 class="card-subtitle text-muted">Add a descriptive tag or two to this destination, so people know what this place is like.</h6><br>
        <%= destinations_fields.fields_for :tags, destinations_fields.object.tags.build do |tags_fields| %>
          <%= tags_fields.label :tag_1 %>
          <%= tags_fields.text_field :title %><br>
          <%= tags_fields.label :tag_2 %>
          <%= tags_fields.text_field :title %><br>
          <%= tags_fields.label :tag_3 %>
          <%= tags_fields.text_field :title %>
        <% end %>
      <% end %>
    </div>
  <br>
</div>

  <div class="card mb-3" style="height: 100%; width:52%; float:right; margin:1px">
    <h3 class="card-header">Add Destinations</h3>
    <div class="card-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">City, State</th>
            <th scope="col">Add/Remove</th>
            <th scope="col"><center>Order</center></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @destinations.each.with_index(1) do |destination, i| %>
            <%= f.fields_for :destination_road_trips, drts_find_or_build(@road_trip, destination) do |drts_fields| %>
              <% if destination.on_this_trip?(@road_trip) %>
                <tr class="table-success">
                  <td><%= destination.name %></td>
                  <td><%= destination.city_state %></td>
                  <td><center><input type="checkbox" value="<%=i%>" name="road_trip[destination_ids][]" id="road_trip_destination_ids_<%=i%>" checked></input></center></td>
                  <td><center><%= drts_fields.number_field :destination_order,  style: 'width: 50%;' %></center></td>
                </tr>
              <% else %>
                <tr class="table-active">
                  <td><%= destination.name %></td>
                  <td><%= destination.city_state %></td>
                  <td><center><input type="checkbox" value="<%=i%>" name="road_trip[destination_ids][]" id="road_trip_destination_ids_<%=i%>"></input></center></td>
                  <td><center><%= drts_fields.number_field :destination_order,  style: 'width: 50%;' %></center></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= f.hidden_field :author_id, value: current_user.id %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-lg btn-block"%>
    <% end %>
  </div>
</div>

app/views/road_trips/edit.html.erb
<h1>Editing Road Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @road_trip %> |
<%= link_to 'Back', road_trips_path %>

app/views/road_trips/index.html.erb
<h1>Road Trips <%= link_to 'Create New Road Trip', new_road_trip_path, {class: "btn btn-primary"} %> </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Completed</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Miles</th>
      <th scope="col">Destinations</th>
      <% if current_user.admin %>
        <th scope="col" colspan="3"><center>Edit User Trips</center></th>
      <% else %>
        <th scope="col" colspan="3"><center>Edit Your Trips</center></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @road_trips.each do |road_trip| %>
      <tr class="table-active">
        <td><% if trip_completed(road_trip) %>
          <span class='badge badge-pill badge-primary'>X</span>
          <% elsif current_user.current_trip == road_trip %>
          <span class='badge badge-pill badge-primary'>In Process</span>
          <% end %>
        </td>
        <td><%= link_to road_trip.title, road_trip_path(road_trip) %></td>
        <td><%= road_trip.description %></td>
        <td><%= road_trip.total_miles %></td>
        <td><center><%= road_trip.total_destinations %></center></td>
        <% if current_user.admin || road_trip.author_id == current_user.id %>
          <td><%= link_to 'Show', road_trip %></td>
          <td><%= link_to 'Edit', edit_road_trip_path(road_trip) %></td>
          <td><%= link_to 'Destroy', road_trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td colspan="3"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/road_trips/new.html.erb
<h1>New Road Trip</h1>

  <%= render 'form' %>

<%= link_to 'Back', road_trips_path %>

app/views/road_trips/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-3">
  <h3 class="card-header"><%= @road_trip.title %></h3>
  <div class="card-body">
    <h5 class="card-title">By: <%= trip_author(@road_trip).username %></h5>
    <h6 class="card-subtitle text-muted">Created At: <%= @road_trip.created_at %> </h6>
    <center><img style="height: 200px; width: 400px; display: block; float:left;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image"></center>
    <div class="form-group" style="float:right;">
      <%= form_for current_user do |f| %>
        <%= f.check_box :current_trip_id %>
        <%= f.label :make_current_trip %><br>
        <%= f.fields_for :user_road_trips, urts_find_or_build(@road_trip, current_user) do |user_road_trip_fields| %>
          <%= user_road_trip_fields.check_box :completed %>
          <%= f.label :mark_as_completed %><br>
        <% end %>
        <%= f.submit "Update", html: { class: "btn btn-primary btn-sm" }%>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @road_trip.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <% @road_trip.destination_road_trips.order(:destination_order).each do |destination_road_trip| %>
      <li class="list-group-item"><%= link_to drt_destination_finder(destination_road_trip).name, destination_path(drt_destination_finder(destination_road_trip)), { style: "float:left;" } %>
        <span class="badge badge-primary" style="float:right;">Stop <%= destination_road_trip.destination_order %></span></li>
    <% end %>
  </ul>
  <div class="card-body">|
    <% @road_trip.tags.uniq.each do |tag| %>
      <%= link_to tag.title, tag_path(tag) %> |
    <% end %>
  </div>
  <div class="card-footer text-muted">
    Last Updated At: <%= @road_trip.updated_at %> |
    <% if current_user.id == @road_trip.author_id %>
      <%= link_to 'Edit', edit_road_trip_path(@road_trip) %> |
    <% end %>

    <%= link_to 'Back', road_trips_path %>
  </div>
</div>