config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pictures
  resources :user_cars
  resources :cars
  resources :destination_tags
  resources :destination_road_trips
  resources :comments
  resources :user_road_trips
  resources :tags
  resources :destinations
  resources :road_trips
  resources :users, path: 'user/profiles'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  belongs_to :current_trip, class_name: 'RoadTrip', foreign_key: 'current_trip_id'
  belongs_to :current_car, class_name: 'Car', foreign_key: 'current_car_id'

  has_many :user_road_trips
  has_many :road_trips, through: :user_road_trips
  has_many :user_cars
  has_many :cars, through: :user_cars
  has_many :pictures, as: :imageable

  def garage
    @garage
  end

  def garage=(car)
    @garage = []
    @garage << car
  end

  def self.road_warriors
    all.order(miles_driven: :desc).limit(10)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin
      @users = User.all
    else
      @users = User.road_warriors
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :current_trip_id, user_road_trips: [:completed])
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def trips_created(user)
    RoadTrip.where(author_id: user.id)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if current_user.admin %>
  <h1> Users </h1>
<% else %>
  <h1>Top Road Warriors</h1>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Miles Driven</th>
      <th scope="col">Current Car</th>
      <th scope="col">Current Trip</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="table-active">
        <th scope="row"><%= link_to user.username, user_path(user) %></td>
        <td><%= user.miles_driven %></td>
        <td><%= link_to find_car(user.current_car_id).make_and_model, car_path(find_car(user.current_car_id)) if user.current_car_id %></td>
        <td><%= link_to find_trip(user.current_trip_id).title, road_trip_path(find_trip(user.current_trip_id)) if user.current_trip_id %></td>
        <% if current_user.admin %>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user.admin %>
  <%= link_to 'Create New User', new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-3">
  <h3 class="card-header"><%= @user.username %></h3>
  <div class="card-body">
    <h5 class="card-title"><%= @user.miles_driven %> Miles Driven</h5>
    <h6 class="card-subtitle text-muted"><%= @user.user_road_trips.size %> Trip(s) Taken</h6>
  </div>
  <center><img style="height: 200px; width: 400px; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image"></center>
  <div class="card-body">
    <p class="card-text">Trips Taken:</p>
  </div>
  <ul class="list-group list-group-flush">
    <% @user.user_road_trips.each do |user_road_trip| %>
      <li class="list-group-item"><%= link_to road_trip_finder(user_road_trip.road_trip_id).title, road_trip_path(road_trip_finder(user_road_trip.road_trip_id)) %>
        <span class="badge badge-pill badge-primary" style="float:right">
          <%= 'Completed' if user_road_trip.completed %>
          <%= 'In Progress' if user_road_trip.road_trip_id = current_user.current_trip_id %>
        </span>
      </li>
    <% end %>
  </ul>
  <div class="card-body">
    <p class="card-text">Trips Created:</p>
  </div>
  <ul class="list-group list-group-flush">
    <% if trips_created(@user).empty? %>
      <li class="list-group-item"><center><%= link_to "Create Some Trips!", new_road_trip_path %></center></li>
    <% end %>
    <% trips_created(@user).each do |trip| %>
      <li class="list-group-item"><%= link_to trip.title, road_trip_path(trip) %></li>
    <% end %>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Comments Made</a>
    <a href="#" class="card-link">Comments Received</a>
  </div>
  <div class="card-footer text-muted">
    Road Warrior Since: <%= @user.created_at %> |
    <% if current_user.admin || current_user == @user %>
      <%= link_to 'Edit', edit_user_path(@user) %> |
    <% end %>
    <%= link_to 'Back', users_path %>
  </div>
</div>