config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pictures
  resources :user_cars
  resources :cars
  resources :destination_tags
  resources :destination_road_trips
  resources :comments
  resources :user_road_trips
  resources :tags
  resources :destinations
  resources :road_trips
  resources :users, path: 'user/profiles'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :street_address, presence: true
  validates :street_address, uniqueness: true

  has_many :destination_tags
  has_many :tags, through: :destination_tags
  has_many :destination_road_trips
  has_many :road_trips, through: :destination_road_trips
  has_many :users, through: :road_trips
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :tags

  def visited
    self.destination_road_trips.count
  end

  def city_state
    "#{self.city}, #{self.state}"
  end

  def top_tag
    self.tags[0]
  end

  def stop_order(road_trip)
    trip = self.destination_road_trips.where(road_trip_id: road_trip.id).first
    trip.destination_order ||= 0
  end

  def on_this_trip?(road_trip)
    !DestinationRoadTrip.where(road_trip_id: road_trip.id).where(destination_id: self.id).empty?
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  def index
    @destinations = Destination.all
  end

  def show
  end

  def new
    @destination = Destination.new
  end

  def edit
  end

  def create
    @destination = Destination.new(destination_params)

    if @destination.save
      redirect_to @destination
    else
      format.html { render :new }
    end
  end

  def update
    if @destination.update(destination_params)
      redirect_to @destination
    else
      render :edit
    end
  end

  def destroy
    @destination.destroy
    redirect_to destinations_url
  end

  private
    def set_destination
      @destination = Destination.find(params[:id])
    end

    def destination_params
      binding.pry
      params.require(:destination).permit(:name, :description, :city, :state, :street_address, tags_attributes: [:title])
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description, size: "75x5" %><br>

  <%= f.label :city %>
  <%= f.text_field :city %> ,

  <%= f.label :state %>
  <%= f.text_field :state %><br>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %><br><br>

  <h6 class="card-subtitle text-muted">Add a descriptive tag or two to this destination, so people know what this place is like.</h6><br>

  <%= f.fields_for :tags, f.object.tags.build do |tags_fields| %>
    <%= tags_fields.label :tag_1 %>
    <%= tags_fields.text_field :title %><br>
    <%= tags_fields.label :tag_2 %>
    <%= tags_fields.text_field :title %><br>
    <%= tags_fields.label :tag_3 %>
    <%= tags_fields.text_field :title %>
  <% end %>

  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Destinations <%= link_to 'Create New Destination', new_destination_path, {class: "btn btn-primary"} %> </h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">City, State</th>
      <th scope="col">Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @destinations.each do |destination| %>
      <tr class="table-active">
        <th scope="row"><%= link_to destination.name, destination_path(destination) %></th>
        <td><%= destination.description %></td>
        <td><%= destination.city_state %></td>
        <td>
          <% destination.tags.each do |tag| %>
            <%= link_to tag.title, tag_path(tag) %>,
          <% end %>
        </td>
        <% if current_user.admin %>
          <td><%= link_to 'Show', destination %></td>
          <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
          <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-3">
  <h3 class="card-header"><%= @destination.name %></h3>
  <div class="card-body">
    <h5 class="card-title"><%= @destination.city %>, <%= @destination.state %></h5>
    <h6 class="card-subtitle text-muted"><%= @destination.street_address %></h6>
  </div>
  <center><img style="height: 200px; width: 400px; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Card image"></center>
  <div class="card-body">
    <p class="card-text"><%= @destination.description %></p>
  </div>
  <p>Tags:</p>
  <ul class="list-group list-group-flush">
    <% if @destination.tags.empty? %>
      <li class="list-group-item"><center><%= link_to "Tag this Destination!", edit_destination_path(@destination) %></center></li>
    <% else %>
      <% @destination.tags.each do |tag| %>
        <li class="list-group-item"><%= link_to tag.title, tag_path(tag) %></li>
      <% end %>
    <% end %>
  </ul>
  <div class="card-body">

  </div>
  <div class="card-footer text-muted">
    Created At: <%= @destination.created_at %> |
      <%= link_to 'Edit', edit_destination_path(@destination) %> |
      <%= link_to 'Back', destinations_path %>
  </div>
</div>