config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#home"
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pictures
  resources :user_cars
  resources :cars
  resources :destination_tags
  resources :destination_road_trips
  resources :comments
  resources :user_road_trips
  resources :tags
  resources :destinations
  resources :road_trips
  resources :users, path: 'user/profiles'

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, presence: true
  validates :model, presence: true
  validates :mpg, presence: true

  has_many :user_cars
  has_many :users, through: :user_cars
  has_many :pictures, as: :imageable

  def make_and_model
    "#{self.make} #{self.model}"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :street_address, presence: true
  validates :street_address, uniqueness: true

  has_many :destination_tags
  has_many :tags, through: :destination_tags
  has_many :destination_road_trips
  has_many :road_trips, through: :destination_road_trips
  has_many :users, through: :road_trips
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :tags

  def visited
    self.destination_road_trips.count
  end

  def city_state
    "#{self.city}, #{self.state}"
  end

  def top_tag
    self.tags[0]
  end

  def stop_order(road_trip)
    trip = self.destination_road_trips.where(road_trip_id: road_trip.id).first
    trip.destination_order ||= 0
  end

  def on_this_trip?(road_trip)
    !DestinationRoadTrip.where(road_trip_id: road_trip.id).where(destination_id: self.id).empty?
  end
end

app/models/destination_tag.rb
class DestinationTag < ActiveRecord::Base
  belongs_to :destination
  belongs_to :tag
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/road_trip.rb
class RoadTrip < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :total_miles, presence: true
  validates :author_id, presence: true

  has_many :user_road_trips
  has_many :users, through: :user_road_trips
  has_many :destination_road_trips
  has_many :destinations, through: :destination_road_trips
  has_many :tags, through: :destinations
  has_many :pictures, as: :imageable
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :destinations
  accepts_nested_attributes_for :destination_road_trips
  accepts_nested_attributes_for :tags

  def total_destinations
    self.destinations.size
  end

  def destinations_attributes=(destination_attributes)
    destination_attributes.values.each do |destination_attribute|
      destination = Destination.find_or_initialize_by(destination_attribute)
      if destination.save
        self.destination_road_trips.create(destination_id: destination.id)
      end
    end
  end

  def destination_road_trips_attributes=(destination_road_trips_attributes)
    trips_to_update = destination_road_trips_attributes.values.select {|destination_road_trip_attribute| !destination_road_trip_attribute[:id].nil?}
    trips_to_update.each do |drt|
      if drt[:destination_order].to_i >= 0 && drt[:destination_order].to_i <= trips_to_update.length
        if !DestinationRoadTrip.where(id: drt[:id]).empty?
          DestinationRoadTrip.where(id: drt[:id]).first.update(destination_order: drt[:destination_order])
        end
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :title, presence: true

  has_many :destination_tags
  has_many :destinations, through: :destination_tags

  def self.popularity_ordered
    joins(:destination_tags).group("destination_tags.tag_id").order("COUNT(destination_tags.tag_id) DESC")
  end

  def popularity
    self.destinations.count
  end

  def last_destination
    if last_association = DestinationTag.where(tag_id: self.id).order(created_at: :desc).limit(1)[0]
      Destination.find(last_association.destination_id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  belongs_to :current_trip, class_name: 'RoadTrip', foreign_key: 'current_trip_id'
  belongs_to :current_car, class_name: 'Car', foreign_key: 'current_car_id'

  has_many :user_road_trips
  has_many :road_trips, through: :user_road_trips
  has_many :user_cars
  has_many :cars, through: :user_cars
  has_many :pictures, as: :imageable

  def garage
    @garage
  end

  def garage=(car)
    @garage = []
    @garage << car
  end

  def self.road_warriors
    all.order(miles_driven: :desc).limit(10)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user_car.rb
class UserCar < ActiveRecord::Base
  belongs_to :user
  belongs_to :car
end

app/models/user_road_trip.rb
class UserRoadTrip < ActiveRecord::Base
  belongs_to :user
  belongs_to :road_trip
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_url
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:make, :model, :mpg)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.popularity_ordered
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_url
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def find_car(id)
    Car.find(id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/road_trips_helper.rb
module RoadTripsHelper
  def find_trip(id)
    RoadTrip.find(id)
  end

  def trip_author(author_id)
    User.find(author_id)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_cars_helper.rb
module UserCarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def trips_created(user)
    RoadTrip.where(author_id: user.id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Road Trip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css">
</head>
<body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Road Trip", root_url, {class: "navbar-brand"} %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation" style="">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto">
        <% if current_user %>
          <li>
            <%= link_to "Road Warriors", users_path, {class: "nav-link"} %>
          </li>
          <li>
            <%= link_to "Trips", road_trips_path, {class: "nav-link"} %>
          </li>
          <li>
            <%= link_to "Destinations", destinations_path, {class: "nav-link"} %>
          </li>
          <li>
            <%= link_to "Tags", tags_path, {class: "nav-link"} %>
          </li>
          <li class="nav-item">

          </li>
          <li class="nav-item dropdown show">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"><%=current_user.username%></a>
            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 44px, 0px);">
              <%= link_to "Select a Car", cars_path, {class: "dropdown-item"}  if current_user.current_car.nil?%>
              <%= link_to "Garage", cars_path, {class: "dropdown-item"}  if current_user.current_car%>
              <%= link_to "Select a Road Trip", road_trips_path, {class: "dropdown-item"} if current_user.current_trip.nil?%>
              <%= link_to "Current Trip", road_trip_path(current_user.current_trip), {class: "dropdown-item"} if current_user.current_trip%>
              <%= link_to "Profile", user_path(current_user), {class: "dropdown-item"} %>
          <!--<%= link_to "Compare", user_path(current_user), {class: "dropdown-item"} %>-->
              <%= link_to "Account", edit_user_registration_path(current_user), {class: "dropdown-item"} %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", destroy_user_session_url, {method: :delete, class: "dropdown-item"} %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <p class="alert"><%= alert %></p>
  <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
</body>
</html>